name: atestsnap
summary: summary
description: |
  description
architectures:
  - amd64

version: '0.1'
base: core22
confinement: strict
grade: stable

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages

apps:
  atestsnap:
    command: bin/python3
    extensions:
      # HINT: Adds plugs and changes environment variables when building and running
      - gnome
    plugs:
      - home
      - network
      - removable-media
      - raw-usb
      - serial-port

parts:
  # libadwaita:
  #   plugin: meson
  #   source: https://gitlab.gnome.org/GNOME/libadwaita/-/archive/1.2.0/libadwaita-1.2.0.tar.bz2
  #   source-checksum: sha256/9da0df3d2f2f5c0a79becd47d09312124542545e4aa1ea151b993c5f6b939e78
  #   override-pull: |
  #     craftctl default
  #     # WORKAROUND: Ignore compiler warning
  #     sed -e 's/-W\(format-nonliteral\)\b/-Wno-\1/g' -i meson.build
  #   meson-parameters:
  #     # WORKAROUND: Must be installed to /usr because of GI search path
  #     - --prefix=/usr
  #     - -Dexamples=false
  #     - -Dtests=false
  #     - -Dvapi=false
  #   stage:
  #     - -usr/include

  atestsnap:
    # Missing optional dependencies atomicparsley, mpv, phantomjs and rtmpdump
    #after: [libadwaita]
    plugin: python
    source: https://github.com/kk7ds/chirp.git
    stage-packages:
      - python3-requests
      - python3-serial
      - python3-six
      - python3-suds
      - python3-future
      - python3-yattag
      - python3-wxgtk4.0
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    override-pull: |
      craftctl default
    override-build: |
      sed -i 's/py3dev/0.0.1' ${SNAPCRAFT_PART_BUILD}/chirp/__init__.py
      craftctl build
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
