name: atestsnap
summary: summary
description: |
  description

architectures:
  - amd64

version: '0.1'
base: core22
confinement: strict
grade: stable

apps:
  atestsnap:
    command: usr/bin/python
    extensions: [gnome-3-38]

parts:
  atestsnap:
    plugin: python
    source: https://github.com/psf/requests.git
